### ISSUE TITLE
Command vendor:publish doesn't create config

### ISSUE THREAD

**Issue by bbashy** [haleks/writedown#1]
The command in the docs doesn't seem to save/copy the file from your source.

```
$ php artisan vendor:publish --provider "Haleks\Writedown\ServiceProvider"
Publishing complete.
```

I'm sure it's down to the package not being ready and you may already know about the issue, but leaving this here incase!

**Comment by haleksandre** [comment]
It's a typo in the documentation. The command should be:

```bash
php artisan vendor:publish --provider "Haleks\Writedown\Writedow
nServiceProvider"
```

Thanks for pointing this out. I'll update the documentation shortly.
