### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by bbashy** [haleks/writedown#2]
Will you be supporting 5.5 when it's released? Automatic package discovery is the main thing.

**Comment by haleksandre** [comment]
Yes,

As of now, it doesn't seem like there are any breaking changes, so technically the latest version as is should work with 5.5.

I'm waiting to see if any breaking changes will be introduced in the official release before I release a version that supports 5.5.

**Comment by timschwartz** [comment]
I get this error during composer update:

    Problem 1

    - Conclusion: remove laravel/framework 5.5.x-dev

    - haleks/writedown 2.0.x-dev requires illuminate/view 5.4.* -> satisfiable by illuminate/view[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.9].`

**Comment by bbashy** [comment]
@timschwartz I believe support hasn't been added yet.

**Comment by timschwartz** [comment]
Thanks.
