### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by bbashy** [haleks/writedown#3]
Are you working on a release for 5.6 or can I start it?

**Comment by bbashy** [comment]
Fantastic, thanks!

**Comment by Chrisx84** [comment]
epic FAIL!

**Comment by bbashy** [comment]
@Chrisx84 ?

**Comment by Chrisx84** [comment]
you asked a legit question and the repo owner just closes this issue without a word so epic fail on that dudes side. kinda makes me ashamed to be canadian having to share this country with such arrogance.

**Comment by bbashy** [comment]
@Chrisx84 No? They closed the issue via their PR https://github.com/haleks/writedown/commit/a606c12854dc9832ba9505d7fa61a3b2098fa6d3

**Comment by Chrisx84** [comment]
still could of said something so others know. dont forget thnx to microsoft, github is about to get alot of new people coming who dont know the little details of github.
